version: '3.3'

networks:
  business-intelligence-net:
    driver: bridge

services:
## --------------------------------------------- APACHE NIFI SECTION --------------------------------------------
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    cap_add:
      - NET_ADMIN # low port bindings
    restart: unless-stopped
    ports:
      - "8080:8080/tcp" # HTTP interface
      # - "8443:8443/tcp" # HTTPS interface
      - "7001:7001/tcp"
      - "514:514/tcp" # Syslog
      - "514:514/udp" # Syslog
      - "2055:2055/udp" # NetFlow
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    expose:
      - 8080
    volumes:
      - ./nifi/conf/volumes:/opt/nifi/nifi-current/jdbc
      - ./nifi/jdbc:/opt/nifi/nifi-current/jdbc
    networks:
      - business-intelligence-net
## --------------------------------------------- END NIFI SECTION --------------------------------------------

## --------------------------------------------- POSTGRES SECTION ---------------------------------------------
  # Database Container (postgres)
  postgres:
    image: postgres
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_USER: shoc
      POSTGRES_PASSWORD: JustKeepSwimming
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - business-intelligence-net

  # Container of PGAdmin (web-based admin tool for postgres database)
  pgadmin:
    container_name: pg_admin
    image: registry1.dso.mil/ironbank/opensource/pgadmin4:7.6
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: shoc@shoc.us
      PGADMIN_DEFAULT_PASSWORD: JustKeepSwimming
    links:
      - postgres
    ports:
      - "3031:80"
    networks:
      - business-intelligence-net
## ------------------------------------------- END POSTGRES SECTION -------------------------------------------
