###################################[ Constants ]######################################

USERNAMEEXPRESSION = "<.*>" # RegEx for usernames contained between <>

SYSTEMUSERNAME = "-!-" # The tag for system messages, change based on system/chat log origins

TIMESTAMPEXPRESSION = "\[[0-9]{2}:[0-9]{2}:[0-9]{2}(\.[0-9]{1,3})?\]" # RegEx for timestamp as [HH:MM:SS.MS]

KEYWORDS = [ # List of key words or phrases to look for, currently being used to test selecting specific chats by "topic"
    'track'
]

STARTINDICATOR = 'posted' # String used to indicate the first time a track is posted

ENDINDICATOR = 'complete' # String used to indicate the track has been resolved

SUBTASKINDICATORS = [ #Strings used to indicate subtasks, likely regex for verbs after POS tagging

]

KEYALIASES = { # Dictionary of Key words with a list of multiple aliases
    'Example': [],
    'Another Example': []
}

ACRONYMS = { # Dictionary of common acronyms used in military IRC communications for substituting acronyms for more naturally readable phrases.
    'ACO': 'airspace control order',
    'ADA': 'air defense artillery',
    'AC': 'attack coordinator',
    'AFTTP': 'Air Force tactics, techniques, and procedures',
    'AI': 'air interdiction',
    'ALSA': 'Air Land Sea Application Center',
    'AMD': 'air mobility division',
    'AO': 'area of operations',
    'AOC': 'air operations center',
    'AOR': 'area of responsibility',
    'ASOC': 'air support operations center',
    'ASR': 'air support request',
    'ATO': 'air tasking order',
    'BCD': 'battlefield coordination detachment',
    'BCT': 'brigade combat team',
    'BDA': 'battle damage assessment',
    'BFT': 'blue force tracker',
    'C2': 'command and control',
    'C2DO': 'command and control duty officer',
    'CAC': 'common access card',
    'CAOC': 'combined air operations center',
    'CAS': 'close air support',
    'CASEVAC': 'casualty evacuation',
    'CFACC': 'combined forces air component commander',
    'CJTF': 'coalition joint task force',
    'CCA': 'close combat attack',
    'CCDR': 'combatant commander',
    'CCO': 'central control officer',
    'COD': 'combat operations division',
    'COP': 'common operational picture',
    'CCSG': 'commander, carrier strike group',
    'CFACC': 'combined force air component commander',
    'CSARDO': 'combat search and rescue duty officer',
    'CSG': 'carrier strike group',
    'DCA': 'defensive counterair',
    'DEC': 'dynamic effects cell',
    'DSN': 'Defense Switched Network',
    'DT': 'dynamic targeting',
    'DTL': 'dynamic targeting list',
    'ESG': 'expeditionary strike group',
    'FARP': 'forward arming and refueling point',
    'FM': 'field manual',
    'FRAGORD': 'fragmentary order',
    'FSE': 'fire support element',
    'GCC': 'Geographic combatant commander',
    'IAW': 'in accordance with',
    'IDN': 'initial distribution number',
    'IED': 'improvised explosive device',
    'INFLTREPS': 'In-flight reports',
    'IO': 'information operations',
    'IODO': 'information operations duty officer',
    'IP': 'internet protocol',
    'ISRD': 'intelligence, surveillance, and reconnaissance division',
    'IT': 'information technology',
    'IWDO': 'Irregular warfare duty officer',
    'J-3': 'operations directorate of a joint staff; operations staff section',
    'J-6': 'communications system directorate of a joint staff; command, control, communications, and computer systems staff section',
    'JADOCS': 'joint automated deep operations coordination system',
    'JFC': 'joint force commander',
    'JOA': 'joint operations area',
    'JP': 'joint publication',
    'JPRC': 'joint personnel recovery center',
    'JSTARS': 'joint surveillance target attack radar system',
    'JTAC': 'joint terminal attack controller',
    'JTF': 'joint task force',
    'Lemay': 'Center Curtis E. LeMay Center for Doctrine Development and Education',
    'LNO': 'liaison officer',
    'LAN': 'local area network',
    'MCCDC': 'Marine Corps Combat Development Center',
    'MCRP': 'Marine Corps reference publication',
    'MEDEVAC': 'medical evacuation',
    'MND-B': 'Multinational Division-Baghdad',
    'MTI': 'moving target indicator',
    'MTTP': 'multi-Service tactics, techniques, and procedures',
    'NECOS': 'net control station',
    'NL': 'non-lethal',
    'NIPRNET': 'non-secure internet protocol router network',
    'NTTP': 'Navy tactics, techniques, and procedures',
    'NWDC': 'Navy Warfare Development Command',
    'ODO': 'operations duty officer',
    'OEF': 'Operation ENDURING FREEDOM',
    'OIF': 'Operation IRAQI FREEDOM',
    'OPLAN': 'operation plan',
    'OPORD': 'operation order',
    'OPTASKCHAT': 'operation task chat',
    'PCHAT': 'persistent chat',
    'PID': 'positive identification',
    'POI': 'point of impact',
    'POO': 'point of origin',
    'PR': 'personnel recovery',
    'RO': 'room owner',
    'ROE': 'rules of engagement',
    'ROZ': 'restricted operations zone',
    'S-3': 'battalion or brigade operations staff officer (Army; Marine Corps battalion or regiment)',
    'S-6': 'communications staff officer',
    'SADO': 'senior air defense officer',
    'SALT': 'size, activity, location, time',
    'SALUTE': 'size, activity, location, unit, time, and equipment',
    'SATCOM': 'satellite communications',
    'SEAD': 'suppression of enemy air defenses',
    'SIDO': 'senior intelligence duty officer',
    'SIGACT': 'significant activity',
    'SIPRNET': 'secret internet protocol router network',
    'SITREP': 'situation report',
    'SODO': 'senior operations duty officer',
    'SOLE': 'special operations liaison element',
    'SOP': 'standard operating procedure',
    'SOR': 'system of record',
    'SUA': 'special use airspace',
    'TACS': 'tactical air control squadron',
    'TAOC': 'Tactical Air Operations Center',
    'TC': 'tactical chat',
    'TIC': 'troops in contact',
    'TOC': 'tactical operations center',
    'TRADOC': 'United States Army Training and Doctrine Command',
    'TST': 'time-sensitive targeting',
    'TTP': 'tactics, techniques and procedures',
    'UAS': 'unmanned aircraft system',
    'UJTL': 'Universal Joint Task List',
    'UNTL': 'Universal Naval Task List',
    'US': 'United States',
    'USSOCOM': 'United States Special Operations Command',
    'VOSIP': 'voice over secure internet protocol'
                 }

ABBREVIATIONS = { # Dictionary of common abbreviations used in military IRC communications to substitute for more naturally readable phrases.
    'abn': 'airborne',
    'arr': 'arrived',
    'a/c': 'aircraft',
    'a/f': 'as fragged or airfield depending on context',
    'affirm': 'affirmative',
    'afk': 'away from keyboard',
    'appr': 'approved',
    'aar': 'after action review',
    'a/s': 'airspace',
    'ata': 'actual time of arrival',
    'atd': 'actual time of departure',
    'att': 'at this time (use "now")',
    'bolo': 'be on the lookout for',
    'c': 'copy (acknowledgment of receipt)',
    'ck': 'check',
    'cip': 'come in please (generally used when initiating whispers)',
    'Clr': 'clear',
    'clrd': 'cleared',
    'canx': 'cancel',
    'comm': 'communications',
    'consol': 'consolidate',
    'c/s': 'call sign',
    'dc': 'disconnected',
    'decon': 'deconflict or decontaminate depending on context',
    'decond': 'deconflicted',
    'dep': 'departed',
    'd/o': 'drop off',
    'dz': 'drop zone',
    'enrt': 'en route',
    'eom': 'end of mission',
    'eta': 'estimated time of arrival',
    'etd': 'estimated time of departure',
    'fc': 'frequency change',
    'fl': 'flight level (altitude in hundreds of feet)',
    'ff': 'flight following',
    'ftr': 'failed to radio',
    'g2w': 'good two way communication',
    'gt': 'good test (reply to a “t” ((test)) connectivity check request)',
    'hc': 'how copy',
    'hvt': 'high value target',
    'i+': '(air refueling) instantaneous fuel available',
    'ib': 'Inbound',
    'IFE': 'in flight emergency',
    'ifr': 'instrument flight rules or in flight report depending on context',
    'imm': 'immediate',
    'iso': 'in support of',
    'ivo': 'in vicinity of',
    'lnd': 'landed',
    'lkp': 'last known position',
    'lz': 'landing zone',
    'max': 'ord maximum ordnance altitude',
    'mc': 'mission complete',
    'msn': 'mission',
    'mt': 'mis-tell (posted info in wrong room)',
    'Mx': 'or maint maintenance',
    'neg': 'negative',
    'nstr': 'nothing significant to report',
    'ob': 'outbound',
    'o/c': 'on channel',
    'o/n': 'operations normal',
    'o/s': 'on station',
    'osr': 'operating outside ROZ',
    'o/t': 'on tank (air refueling)',
    'pls': 'please',
    'poi': 'point of injury/impact',
    'poo': 'point of origin',
    'pos': 'position',
    'pri': 'priority',
    'rcvr': 'aircraft receiving air refueling',
    'rhr': 'ROZ hot request',
    'rip': 'relief in place',
    'rqst': 'request',
    'rgr': 'roger',
    'rp': 'release point',
    'rnds': 'rounds',
    'ron': 'remain overnight',
    'roz': 'restricted operating zone',
    'rtb': 'return to base',
    'rtd': 'return to duty',
    'rtn': 'routine',
    'r/r': 'radar/IFF contact and radio communication established',
    'rx': 'receive',
    'sod': 'safe on deck',
    'stby': 'standby (does not imply “working”)',
    'SIPR': 'Secret Internet Protocol Relay (secure network)',
    'sof': 'special operations forces',
    'sp': 'start point',
    's/f': 'show of force',
    'sfc': 'surface',
    't': 'test (request for a connectivity check)',
    'thx': 'thank you',
    'TIC': 'troops in contact',
    't/o': 'takeoff',
    'tn': 'datalink track number',
    'tot': 'time on target',
    'TST': 'time sensitive target',
    'tx': 'transmit',
    'unk': 'unknown',
    'urg': 'urgent',
    'urgsurg': 'urgent surgical',
    'VFR': 'visual flight rules',
    'w/d': 'wheels down',
    'wkg': 'working (standby implied)',
    'wrt': 'with regard to',
    'wspr': 'Whisper',
    'w/u': 'wheels up',
    'wx': 'Weather',
    'yw': "you're welcome",
    '*': '(single asterisk) used to make an immediate correction to previous posting',
    '***': '(three asterisks) used to denote a VIP onboard a specific a/c',
    '.': '(period) used to check server connectivity; no reply is required'
}



######################################################################################